### ISSUE TITLE
Automated E2E Tests

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/knora-api-js-lib-test#2]
related to https://github.com/dhlab-basel/knora-api-js-lib/issues/48

**Comment by tobiasschweizer** [comment]
There is a known issue in protractor with the Chrome version: https://github.com/angular/protractor/issues/5289#issuecomment-517261124

**Comment by tobiasschweizer** [comment]
@subotic I would like to run e2e tests on travis. Could you help me set up an instance of graphdb, Knora and Sipi? Something like 

https://github.com/dhlab-basel/Knora/blob/fb7adba749bf6b37ed36f49f2d6cb3f553b92382/.travis.yml#L108-L126

**Comment by subotic** [comment]
yes, but next week when I'm back. I would rather do it using Github CI.

**Comment by tobiasschweizer** [comment]
> yes, but next week when I'm back

Haven't you cloned yourself yet? :-)

**Comment by tobiasschweizer** [comment]
fix chromedriver version problem: 

- `./node_modules/protractor/bin/webdriver-manager update`
-  `npm i webdriver-manager@latest`

**Comment by tobiasschweizer** [comment]
https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/continuous-integration.md

https://medium.com/@ali.dev/how-to-setup-angular-end-to-end-testing-with-headless-chrome-on-travis-ci-5576767a824a
